Site optimisation
owner6/project1 pull request #3
Opened 2022-09-30 18:23 UTC by owner6

2022-10-03 14:10 UTC, Dever4eg commented on html/1woodEnergyConverter.html
>                </p>
Did you forget to remove `</p>` ?

2022-10-03 14:11 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <input type="text" class="" id="num">
Why did you add an empty class attribute?

2022-10-03 14:12 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <button onclick="know()" class="">Узнайте</button>
It it better to add button click handler in the js code, not in the html

2022-10-03 14:12 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <p><span id="result"></span></p>
Same as before, you can change id to **result**Something

2022-10-03 14:16 UTC, Dever4eg requested changes

2022-10-03 14:16 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <input type="text1" class="" id="exam">
Empty class again

2022-10-03 14:16 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <input type="text1" class="" id="exam">
What is `text1`?

2022-10-03 14:16 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <p><span id="result1"></span></p>
`result1` - is not a good name

2022-10-03 14:16 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +
Unnecessary empty line

2022-10-03 14:16 UTC, Dever4eg commented on html/contacts.html
> +</html>
No newline in the end of file

2022-10-03 14:16 UTC, Dever4eg commented on html/help.html
> +</html>
No newline in the end of file

2022-10-03 14:16 UTC, Dever4eg commented on scrypt.js
> +  var e,p,r;
Better to use `const` or `let` instead of `var`

2022-10-03 14:16 UTC, Dever4eg commented on scrypt.js
> +  e = parseInt(e);
Bad variables name. Better to use some words that describe these vars

2022-10-03 14:16 UTC, Dever4eg commented on scrypt.js
> +
Three empty lines instead of one

2022-10-16 19:25 UTC, owner6 commented on html/1woodEnergyConverter.html
>                </p>
removed "</p>"

2022-10-16 19:30 UTC, owner6 commented on html/1woodEnergyConverter.html
> +              <input type="text" class="" id="num">
removed empty attribute

2022-10-16 20:46 UTC, owner6 commented on html/1woodEnergyConverter.html
> +              <button onclick="know()" class="">Узнайте</button>
renamed all variables and identifiers to correct ones

2022-10-16 20:46 UTC, owner6 commented on html/1woodEnergyConverter.html
> +              <p><span id="result"></span></p>
renamed all variables and identifiers to correct ones

2022-10-16 22:46 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <input type="text" class="" id="num">
I can still see `class=""` in the code

2022-10-16 22:48 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <button onclick="know()" class="">Узнайте</button>
I mean to add click handler like this:
![telegram-cloud-photo-size-2-5359599945792995471-y](https://user-images.githubusercontent.com/16056824/196062132-4700da9f-b46a-4a19-aae6-50191e57dbc9.jpg)

2022-10-16 22:49 UTC, Dever4eg commented on html/1woodEnergyConverter.html
> +              <p><span id="result"></span></p>
But it is still `id="result"`, not `id="wood-heigth-result"`, or smth like that. Did you just forget to push your changes?

2023-02-28 00:19 UTC, closed without merging